

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CADSUS_API_PORT}:8000"
    volumes:
      - ./logs:/app/logs
      - /etc/cisbaf-setup/.certificate-cisbaf.pfx:/app/.certificate-cisbaf.pfx
    env_file:
      - /etc/cisbaf-setup/envs/.env-cadsus-api
    mem_limit: 500m
    cpus: 1.0